In [ ]:

# A tensor is a multi-dimensional array used in Machine Learning and Deep Learning (especially in frameworks like TensorFlow and PyTorch). The dimensions (or ranks) of tensors define their shape and complexity.

In [ ]:
# 0D tensor or Scalar

In [3]:
import numpy as np


In [7]:
zero_D=np.array(2)
zero_D

array(2)

In [9]:
zero_D.ndim
# 0 dimension means o tensor or scalar

0

In [ ]:
# one Tensor is also known as:
# 1.1 D array
# 2. Vector
# 3. ndim=1
# 1 D tesnor is a collection of Scalar

In [11]:
one_D=np.array([2,3,4,6])
one_D

array([2, 3, 4, 6])

In [13]:
one_D.ndim

1

In [ ]:
# no of axis=rank=no of dimension

In [ ]:
# 2 D tensors(matrics)
# collections of vectors
# rank(axis)=2
# rows and column

In [15]:
two_D=np.array([[2,3,5],[5,6,8]])
two_D

array([[2, 3, 5],
       [5, 6, 8]])

In [17]:
two_D.ndim

2

In [ ]:
#  3D Tensor (3rd Order Tensor)
# 🔹 Shape: (Depth × Height × Width) → Example: 4 × 3 × 3
# 🔹 Representation: A collection of 2D matrices stacked together.
# 🔹 Use Case: RGB images (where each channel Red, Green, and Blue is a 2D matrix).

In [19]:
three_D=np.array([[[3,4,5],[5,6,8],[7,8,9]]])
three_D

array([[[3, 4, 5],
        [5, 6, 8],
        [7, 8, 9]]])

In [21]:
three_D.ndim

3

In [ ]:
# 4D Tensor (4th Order Tensor)
# 🔹 Shape: (Batch Size × Depth × Height × Width)
# 🔹 Representation: A collection of 3D tensors stacked together.
# 🔹 Use Case: A batch of multiple RGB images (used in CNNs).

In [37]:
# 3D tensor ko 4D aur 5D tensor mein convert karne ke liye, hum np.expand_dims() ka use karenge.It add extra one axis to the given axis.

In [29]:
four_D = np.expand_dims(three_D, axis=0)
print(four_D.shape)  # Output: (1, 1, 3, 3)

(1, 1, 3, 3)


In [33]:
four_D.ndim

4

In [39]:
four_D = np.array([
    [  # First batch
        [[1, 2, 3], [4, 5, 6], [7, 8, 9]],    # First depth
        [[10, 11, 12], [13, 14, 15], [16, 17, 18]],  # Second depth
        [[19, 20, 21], [22, 23, 24], [25, 26, 27]]   # Third depth
    ],
    [  # Second batch
        [[28, 29, 30], [31, 32, 33], [34, 35, 36]], 
        [[37, 38, 39], [40, 41, 42], [43, 44, 45]], 
        [[46, 47, 48], [49, 50, 51], [52, 53, 54]]
    ]
])

print(four_D.shape)  # Output: (2, 3, 3, 3)
print(four_D)

(2, 3, 3, 3)
[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]
   [25 26 27]]]


 [[[28 29 30]
   [31 32 33]
   [34 35 36]]

  [[37 38 39]
   [40 41 42]
   [43 44 45]]

  [[46 47 48]
   [49 50 51]
   [52 53 54]]]]


In [ ]:
#  5D Tensor (5th Order Tensor)
# 🔹 Shape: (Batch Size × Time Steps × Depth × Height × Width)
# 🔹 Representation: A collection of 4D tensors stacked together.
# 🔹 Use Case: Video processing (where each frame is an image, and multiple frames are stacked together).

In [31]:
five_D = np.expand_dims(four_D, axis=0)
print(five_D.shape)  # Output: (1, 1, 3, 3)

(1, 1, 1, 3, 3)


In [35]:
five_D.ndim

5